### PR TITLE
Fixed some redefinition questions caused by the skel.c file and some …

### PR DESCRIPTION
**Pull request by libo3019**
…code.

Fixed the output executable filenames as bison.exe and flex.exe.

### CODE REVIEW

**Comment by GitMensch** [comment]
The change of the binary names is something I've thought about before, but it is a quite intrusive change, likely breaking people's build scripts. too (actually the one I use check for win_bison in PATH and fallback to bison if not found, but I guess this won't be true for many others).
If we apply this then the build rules https://github.com/lexxmark/winflexbison/tree/master/custom_build_rules needs to be adjusted for the new name, too.
It _would_ remove additional symlinks that are currently needed when using the binaries with configure or similar scripts that only look for "bison" and "flex" and for possibly re-integrating the testsuites, so I'm not "against this" in general.

In any case I'd suggest to not mix that with the redefinitions but keep that as separate PR.

As this repo says the code depends on "Visual Studio 2015 or newer" and all those are covered with the CI which passes I'd merge the PR for this part directly, can I suggest you to force-push that?

**Comment by libo3019** [comment]
What you said is reasonable, but the names can be used well if using the flex.exe and bison.exe. Another question is that although the redefinition has already occurred but it can be avoided. If you think the win port version must keep same with the original version, what you said makes sense.


In my working computer, I am using the modified version. Some compiler warnings perhaps cause others to think that my software exists some bugs. So I do the modification.


If you don't want to merge these modification, I have no opinion. My modification for winbisonflex is only a suggestion.


Thank you for your reply.




| |
libo_3019
|
|
libo_3019@126.com
|
签名由网易邮箱大师定制
On 10/27/2020 20:56，Simon Sobisch<notifications@github.com> wrote：

The change of the binary names is something I've thought about before, but it is a quite intrusive change, likely breaking people's build scripts. too (actually the one I use check for win_bison in PATH and fallback to bison if not found, but I guess this won't be true for many others).
If we apply this then the build rules https://github.com/lexxmark/winflexbison/tree/master/custom_build_rules needs to be adjusted for the new name, too.
It would remove additional symlinks that are currently needed when using the binaries with configure or similar scripts that only look for "bison" and "flex" and for possibly re-integrating the testsuites, so I'm not "against this" in general.

In any case I'd suggest to not mix that with the redefinitions but keep that as separate PR.

As this repo says the code depends on "Visual Studio 2015 or newer" and all those are covered with the CI which passes I'd merge the PR for this part directly, can I suggest you to force-push that?

**Comment by lexxmark** [comment]
I added "win_" prefix to flex/bison tool names at the very beginning. Now it's a part of "legacy" that we have nd many tools rely on that. File renaming or name aliasing are quite easy options in many build systems to adopt "non-standard" win_flex/win_bison names. So I don't think I agree to change tool names now.

Regards your second proposal I think it should be done in the upstream projects. The amount of differences between winflexbison and upstream projects is constantly increasing and it's becoming harder upgrade winflexbison. So I prefer to avoid making differences until they are essential.

I think your fork of winflexbison would be beneficial for someone and it was worth doing it.

**Review by lexxmark — COMMENTED** [review]
I think changes in *.c and *.h files should go to upstream projects.
Changes in *.vcxproj files shouldn't be merged because could break existing scripts.

**Comment by GitMensch** [comment]
> I think changes in *.c and *.h files should go to upstream projects.

I completely agree. As you've inspected the changes already - can you send those upstream?

**Comment by lexxmark** [comment]
> As you've inspected the changes already - can you send those upstream?
I don't face such problems in the winflexbison project now. May be I experienced it in the beginning and just disabled such warnings in C++ settings (I don't remember actually).

Anyway I don't sure there are such problems under Linux (GCC or Clang) in the upstream project. If you have access to linux PC could you please check it? May be there is nothing to fix there.

**Pull request closed without merging**
