### PR TITLE
Fix runtime error upon multiple flex processes

### PR DESCRIPTION
**Pull request by jonnysoe**

### CODE REVIEW

**Comment by jonnysoe** [comment]
This is the fix for issue #86

**Comment by GitMensch** [comment]
Thank you, one issue less :-)

**Comment by mathstuf** [comment]
Are there any plans to cut a release with this included?

**Comment by m-kuhn** [comment]
> Are there any plans to cut a release with this included?

@GitMensch @lexxmark any chance for a release here?

**Comment by mathstuf** [comment]
Semi-annual bump request for a release which includes this PR :) .

**Comment by mathstuf** [comment]
I've added it to our "ci-utilities" repo where we build stuff for our usage. If anyone wants to use it, you can find it here: https://gitlab.kitware.com/utils/ci-utilities/-/releases/winflexbison%2Fv2.5.25.g300f48b-20250321.0

**Pull request merged**
