### PR TITLE
Add CPack configuration / Build AppVeyor Artifacts

### PR DESCRIPTION
**Pull request by Croydon**
The artifacts can be downloaded from the artifacts tab in the AppVeyor jobs.

### CODE REVIEW

**Comment by GitMensch** [comment]
Looks good and will be merged.
For the current artifacts one thing is missing - copying of "custom_build_rules" to bin/release before it is used for packing.
As I don't use CPack or CMake I don't know how to do this. Can you add this, please?

**Comment by lexxmark** [comment]
I've just added "--config Release" to build correct configuration

**Comment by GitMensch** [comment]
@lexxmark Can you include the custom_build_rules to the artifacts (copying them to bin/Release|bin/Debug before packaging), please?

**Comment by Croydon** [comment]
Why is a release build needing custom_build_rules?

**Comment by Croydon** [comment]
> I've just added "--config Release" to build correct configuration

This is wrong. I'm noticing that the debug artifacts are broken and I'm going to try to fix them later. But now you just build everything with Release even in the debug jobs.

**Comment by GitMensch** [comment]
@Croydon They are integrated with the normal releases because these are the way WinFlexBison binaries are most often integrated into VS. A dev artifact package should be identical to a release package if possible (nice side effect: you can get updates to these (or its docs) before an actual release is made).

**Comment by GitMensch** [comment]
Thank you for your work on this, now also including everything that is part of the release.
One last thing to ask: is it possible to include the environment name in the artifact? Suggestion:
win_flex_bison-dev-2013, win_flex_bison-dev-2017x64, win_flex_bison-dev-2017_debug, win_flex_bison-dev-2017x64_debug, ...

**Pull request merged**
